Repository bellshade/Python, pull requests merged in 2021-12, with the labels that each got.

#177 Inheritance
  DIRECTORY.md
  object_oriented_programming/intermediate/inheritance/README.md
  object_oriented_programming/intermediate/inheritance/inheritance.py
Labels: ready-to-merge, python files, markdown files, request tim python untuk review, sudah dirieview!

#178 Abstraksi
  DIRECTORY.md
  object_oriented_programming/intermediate/abstraksi/README.md
  object_oriented_programming/intermediate/abstraksi/abstraksi.py
Labels: ready-to-merge, python files, markdown files, request tim python untuk review, sudah dirieview!

#179 feat: tambah algoritma binary search tree
  struktur_data/binary_search_tree.py
Labels: ready-to-merge, enhancement, python files, request tim python untuk review, sudah dirieview!

#190 feat: fungsi untuk menangani bilangan prima
  DIRECTORY.md
  math/prime_number_library.py
Labels: ready-to-merge, enhancement, python files, markdown files, request tim python untuk review, sudah dirieview!

#193 docs: tambah penjelasan tentang binary tree dan binary search tree
  struktur_data/tree/README.md
  struktur_data/tree/binary_search_tree/README.md
  struktur_data/tree/binary_search_tree/binary_search_tree.py
  struktur_data/tree/binary_search_tree/img/bst_example.png
  struktur_data/tree/binary_search_tree/img/bst_insertion.png
  struktur_data/tree/binary_search_tree/img/inorder.png
  struktur_data/tree/binary_search_tree/img/postorder.png
  struktur_data/tree/binary_search_tree/img/preorder.png
  struktur_data/tree/img/Ilustrasi_BST.png
  struktur_data/tree/img/complete_bt.png
  struktur_data/tree/img/degenerate_bt.png
  struktur_data/tree/img/full_bt.png
  struktur_data/tree/img/height_of_tree.png
  struktur_data/tree/img/perfect_bt.png
Labels: ready-to-merge, documentation, python files, markdown files, request tim python untuk review, sudah dirieview!

#192 feat: menambahkan algoritma incremental_root_search
  algorithm/arithmetic_analysis/rootsearch.py
Labels: ready-to-merge, enhancement, python files, request tim python untuk review, sudah dirieview!
