Repository bellshade/Python, pull requests merged in 2021-11, with the labels that each got.

#145 feat: tambah script untuk menghitung radian
  DIRECTORY.md
  math/radian.py
Labels: ready-to-merge, enhancement, python files, markdown files, request docs team untuk review, request tim python untuk review

#153 feat: pangkat dengan rekursif
  DIRECTORY.md
  math/recursion_power.py
Labels: ready-to-merge, enhancement, python files, markdown files, request docs team untuk review, request tim python untuk review

#151 docs: minor changes
  Basic/README.md
  README.md
  assets/logo.png
Labels: documentation, markdown files, request docs team untuk review

#157 fix: optimisasi dan penambahan docstring ke isPrime.py
  math/is_prime.py
  other/isPrime.py
Labels: ready-to-merge, bug, python files, request tim python untuk review

#159 Walrus
  Basic/04_operator/operator_penugasan_ekspresi.py
  DIRECTORY.md
Labels: ready-to-merge, python files, markdown files, request tim python untuk review

#160 feat: tambah script untuk singly linked list
  DIRECTORY.md
  struktur_data/singly_linked_list.py
Labels: ready-to-merge, enhancement, python files, markdown files, request tim python untuk review

#158 add: menambahkan `PaginationHelper.py`
  web_programming/PaginationHelper.py
Labels: ready-to-merge, add, python files, request tim python untuk review

#162 feat: tambah script doubly linked list
  struktur_data/doubly_linked_list.py
Labels: ready-to-merge, enhancement, python files, request tim python untuk review

#163 add: menambahkan `breadcrumb_generator.py`
  web_programming/breadcrumb_generator.py
Labels: ready-to-merge, add, python files, request tim python untuk review

#166 Link materi selanjutnya
  algorithm/arithmetic_analysis/README.md
  algorithm/backtracking/README.md
  algorithm/boolean_algebra/README.md
  algorithm/divide_and_conquer/README.md
  algorithm/fuzzy_logic/README.md
  algorithm/genetic_algo/README.md
  algorithm/manipulasi_bit/README.md
  algorithm/matrix/README.md
  algorithm/networking_flow/README.md
  algorithm/searching/README.md
  implementation/blockchain/README.md
  implementation/celular_automata/README.md
  implementation/chiper/README.md
  implementation/compression/README.md
  implementation/electro/README.md
  implementation/file_transfer/README.md
  implementation/fractal/README.md
  implementation/geodesy_egineering/README.md
  implementation/linear_algebra/README.md
  implementation/physics/README.md
  math/README.md
  object_oriented_programming/README.md
  object_oriented_programming/basic_oop/0_definisi_kelas/README.md
  object_oriented_programming/basic_oop/1_atribut_kelas/README.md
  other/README.md
  struktur_data/README.md
  web_programming/README.md
Labels: ready-to-merge, markdown files

#165 add: menambahkan `rgb_to_hex.py`
  other/rgb_to_hex.py
Labels: ready-to-merge, add, python files, request tim python untuk review

#167 feat: memperbaiki `Palindrom.py`
  other/Palindrom.py
  other/is_palindrom.py
Labels: ready-to-merge, enhancement, python files, request tim python untuk review

#169 add: tambah embed link kelas terbuka di markdown
  Basic/04_operator/README.md
  Basic/16_class/README.md
  Basic/17_inheritance/README.md
  object_oriented_programming/README.md
Labels: ready-to-merge, add, markdown files

#168 add: menambahkan `hex_to_rgb.py`
  other/hex_to_rgb.py
Labels: ready-to-merge, add, python files, request tim python untuk review

#175 add: menambahkan `get_random_quote.py`
  web_programming/get_random_quote.py
Labels: ready-to-merge, add, python files, request tim python untuk review

#152 add:list and dictionary comprehension
  Basic/25_list_and_dict_comprehension/dict_comprehension.py
  Basic/25_list_and_dict_comprehension/list_comprehension.py
  DIRECTORY.md
Labels: ready-to-merge, python files, markdown files, request docs team untuk review, request tim python untuk review, sudah dirieview!
