Repository bellshade/Python, pull requests merged in 2021-09, with the labels that each got.

#19 Perubahan Konversi Binary ke String
  conversion/binary_to_string.py
Labels: bug, documentation

#22 Tambahkan Config untuk flake8
  .flake8
  .github/workflows/pythonapp.yml
  CONTRIBUTING.md
Labels: documentation, enhancement

#24 Tambahkan Pipeline untuk Format Otomatis
  .github/workflows/pythonapp.yml
  dev-requirements.txt
Labels: enhancement

#21 Implement searching algorithms
  searching/_types.py
  searching/binary_search.py
  searching/linear_search.py
Labels: enhancement

#30 Update docs
  CONTRIBUTING.md
Labels: documentation, enhancement

#31 add: tipe_data python
  Basic/tipe_data/tipe_data.py
Labels: enhancement, basic

#39 Task/fungsi
  Basic/fungsi/README.md
  Basic/fungsi/fungsi.py
Labels: enhancement
