Repository bellshade/Python, pull requests merged in 2021-08, with the labels that each got.

#14 docs: memperbaiki contributing
  CONTRIBUTING.md
Labels: Ok to merge, documentation, enhancement

#15 Update README.md not merge
  chiper/README.md
Labels: automerge, documentation, enhancement

#16 add: menambahkan konversi bilangan binary ke oktal
  conversion/binary_to_octal.py
Labels: enhancement

#17 docs: menambahkan komentar penjelasan pada kode
  genetic_algo/basic_string.py
Labels: automerge, merge when passing
