Repository bellshade/Python, pull requests merged in 2022-10, with the labels that each got.

#202 docs: Penambahan Action Table of Content dan perbaikan penulisan
  Basic/01_introduction/README.md
Labels: documentation, markdown files

#205 docs: penambahan file code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation, markdown files

#203 docs: Penambahan Table of Content ,perbaikan penulisan dan menambahkan kode pada file tipe data
  Basic/01_introduction/README.md
  Basic/02_tipe_data/README.md
  Basic/02_tipe_data/tipe_data.py
Labels: documentation, python files, markdown files, request tim python untuk review

#209 docs: Merevisi README materi ke 4
  Basic/02_tipe_data/README.md
  Basic/03_variable/README.md
  Basic/03_variable/string_variable.py
  Basic/03_variable/variable.py
  Basic/04_operator/README.md
Labels: ready-to-merge, documentation, python files, markdown files, request tim python untuk review, HACKTOBERFEST-ACCEPTED

#211 docs: memperbaiki visitor badge
  README.md
Labels: documentation, markdown files, HACKTOBERFEST-ACCEPTED

#212 docs: memperbaiki readme materi string
  Basic/01_introduction/README.md
  Basic/02_tipe_data/README.md
  Basic/03_variable/README.md
  Basic/04_operator/README.md
  Basic/05_string/README.md
  Basic/05_string/string_python.py
Labels: documentation, python files, markdown files, request tim python untuk review
