Repository bellshade/Python, pull requests merged in 2023-04, with the labels that each got.

#257 add: menambahkan algoritma baru
  implementation/statistic/covariance.py
Labels: ready-to-merge, python files, request tim python untuk review

#258 feat: menambahkan fungsi logistik regressi
  DIRECTORY.md
  implementation/artificial_intelligence/logistic_regression.py
Labels: ready-to-merge, python files, markdown files, request tim python untuk review

#261 feat: menambahkan distribusi multivariate
  implementation/statistic/correlation.py
  implementation/statistic/normalDistribution_multivariate.py
Labels: ready-to-merge, python files, request tim python untuk review

#260 K nearest neighbour
  DIRECTORY.md
  implementation/artificial_intelligence/k_nearest_neighbour.py
Labels: python files, markdown files, request tim python untuk review

#262 feat: menambahkan distribusi multivariate
  implementation/statistic/multivariate_normal.py
Labels: ready-to-merge, python files, request tim python untuk review

#263 feat: menambahkan fungsi skoring
  DIRECTORY.md
  implementation/artificial_intelligence/fungsi_skoring.py
Labels: ready-to-merge, python files, markdown files, request tim python untuk review
