Repository bellshade/Python, pull requests merged in 2023-02, with the labels that each got.

#233 penambahan fungsi variance
  math/variance.py
Labels: python files, request tim python untuk review

#236 Backtracking all combinations
  DIRECTORY.md
  algorithm/backtracking/all_combinations.py
Labels: python files, markdown files, request tim python untuk review

#237 add: menambahkan algoritma baru
  math/fibonacci.py
Labels: ready-to-merge, python files, request tim python untuk review

#240 feat: menambahkan list comprehension
  Basic/25_list_and_dict_comprehension/list_comprehension.py
Labels: ready-to-merge, python files, request tim python untuk review

#242 feat: menambahkan algoritma baru r2_score
  math/r2_score.py
Labels: ready-to-merge, python files, request tim python untuk review
