Repository bellshade/Python, pull requests merged in 2023-03, with the labels that each got.

#243 Audio response
  DIRECTORY.md
  implementation/audio_filter/audio_response.py
Labels: ready-to-merge, python files, markdown files, request tim python untuk review

#245 feat:Menambahkan algoritma mean,media,modus
  implementation/statistic/median.py
  implementation/statistic/modus.py
  implementation/statistic/rata_rata.py
  implementation/statistic/standard_deviasi.py
Labels: ready-to-merge, python files, request tim python untuk review

#244 fix: mengurangi kompleksitas kode
  algorithm/backtracking/cari_kata.py
Labels: ready-to-merge, python files, request tim python untuk review

#247 chore: update folder dan menambahkan fungsi pada kecerdasan buatan
  DIRECTORY.md
  implementation/artificial_intelligence/gradient_descent.py
  implementation/artificial_intelligence/linear_regression.py
Labels: ready-to-merge, python files, markdown files, request tim python untuk review

#248 Decision tree
  DIRECTORY.md
  implementation/artificial_intelligence/decision_tree.py
Labels: python files, markdown files, request tim python untuk review

#249 feat: menambahkan algoritma variance,entropy dan information gain
  implementation/statistic/entropy.py
  implementation/statistic/information_gain.py
  implementation/statistic/variance.py
Labels: ready-to-merge, python files, request tim python untuk review

#254 Kmeans clutser
  DIRECTORY.md
  implementation/artificial_intelligence/k_means_clutser.py
  requirements.txt
Labels: python files, markdown files, request tim python untuk review

#255 feat:menambah algoritma baru
  implementation/fuzzy_logic/fuzzy_logic.py
  requirements.txt
Labels: ready-to-merge, python files, request tim python untuk review

#256 feat: menambahkan long short term memory
  DIRECTORY.md
  implementation/artificial_intelligence/dataset_lstm.csv
  implementation/artificial_intelligence/lstm.py
Labels: ready-to-merge, python files, markdown files, request tim python untuk review, false-positive-merge
