Repository bellshade/Python, pull requests merged in 2023-07, with the labels that each got.

#284 feat: menambahkan lasso Regession
  implementation/artificial_intelligence/lasso_regession.py
Labels: ready-to-merge, python files, request tim python untuk review

#286 feat: menambahkan algoritma quick sort
  DIRECTORY.md
  algorithm/sorting/quick_sorting.py
Labels: ready-to-merge, python files, markdown files, request tim python untuk review

#289 feat: menambah algoritma sinus
  math/sin.py
Labels: ready-to-merge, python files, request tim python untuk review

#292 feat: menambahkan algoritma similarity_search
  DIRECTORY.md
  implementation/artificial_intelligence/similarity_searching.py
Labels: python files, markdown files, request tim python untuk review
