Repository bellshade/Python, pull requests merged in 2023-06, with the labels that each got.

#272 Menambahkan Algoritma pengklasifikasi Hutan Acak #271
  implementation/artificial_intelligence/random_forest.py
Labels: python files, request tim python untuk review

#273 feat: menambahkan algoritm counter(yaudah)
  math/counter.py
Labels: ready-to-merge, python files, request tim python untuk review

#275 fix: memperbaiki beberapa kode yang terbaca warning dan error pada LG…
  .pre-commit-config.yaml
  Basic/08_perulangan/while_loop.py
  implementation/artificial_intelligence/k_means_clutser.py
  implementation/linear_algebra/conjugate_gradient.py
  struktur_data/tree/binary_search_tree/binary_search_tree.py
Labels: python files, request tim python untuk review

#279 fix: update logika baru
  math/persamaan_kuadarat_bilangan_kompleks.py
Labels: ready-to-merge, python files, request tim python untuk review

#280 feat: menambahkan algorith random
  math/random_generator.py
Labels: ready-to-merge, python files, request tim python untuk review, sudah dirieview!

#281 fix: update mergify configuration
  .mergify.yml
Labels: ready-to-merge, good first issue, sudah dirieview!

#282 feat: update algoritma ridge regession
  implementation/artificial_intelligence/rigde_regession.py
Labels: ready-to-merge, python files, request tim python untuk review

#283 feat: menambahkan materi tentang dekorator
  Basic/26_dekorator/README.md
  Basic/26_dekorator/dekorator.py
  Basic/README.md
  DIRECTORY.md
Labels: ready-to-merge, python files, markdown files, request tim python untuk review
